# Generated by Django 4.2.23 on 2025-07-20 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.CharField(choices=[('birchgrove', 'Birchgrove'), ('bonymaen', 'Bonymaen'), ('brynmill', 'Brynmill'), ('clydach', 'Clydach'), ('cockett', 'Cockett'), ('dunvant', 'Dunvant'), ('gorseinon', 'Gorseinon'), ('gower', 'Gower'), ('gowerton', 'Gowerton'), ('hafod', 'Hafod'), ('killay', 'Killay'), ('landore', 'Landore'), ('llansamlet', 'Llansamlet'), ('loughor', 'Loughor'), ('morriston', 'Morriston'), ('morriston_hospital_area', 'Morriston Hospital Area'), ('mumbles', 'Mumbles'), ('penlan', 'Penlan'), ('port_tennant', 'Port Tennant'), ('sketty', 'Sketty'), ('st_thomas', 'St Thomas'), ('swansea_city_centre', 'Swansea City Centre'), ('townhill', 'Townhill'), ('uplands', 'Uplands'), ('west_cross', 'West Cross')], default='swansea_city_centre', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
