SWANSEA_AREAS = [
    ('birchgrove', 'Birchgrove'),
    ('bonymaen', 'Bonymaen'),
    ('brynmill', 'Brynmill'),
    ('clydach', 'Clydach'),
    ('cockett', 'Cockett'),
    ('dunvant', 'Dunvant'),
    ('gorseinon', 'Gorseinon'),
    ('gower', 'Gower'),
    ('gowerton', 'Gowerton'),
    ('hafod', 'Hafod'),
    ('killay', 'Killay'),
    ('landore', 'Landore'),
    ('llansamlet', 'Llansamlet'),
    ('loughor', 'Loughor'),
    ('morriston', 'Morriston'),
    ('morriston_hospital_area', 'Morriston Hospital Area'),
    ('mumbles', 'Mumbles'),
    ('penlan', 'Penlan'),
    ('port_tennant', 'Port Tennant'),
    ('sketty', 'Sketty'),
    ('st_thomas', 'St Thomas'),
    ('swansea_city_centre', 'Swansea City Centre'),
    ('townhill', 'Townhill'),
    ('uplands', 'Uplands'),
    ('west_cross', 'West Cross'),
]

